/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tetris.display;

import java.awt.Component;
import java.util.Dictionary;
import java.util.Hashtable;
import javax.swing.JLabel;

/**
 *
 * @author Skulsinlapakit
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    private static boolean isPause = false;
    private static boolean is2Player = false;
    
    public MainFrame() {
        
        Dictionary<Integer, Component> labelTable = new Hashtable<Integer, Component>();
        labelTable.put(0, new JLabel("Small"));
        labelTable.put(50, new JLabel("Medium"));
        labelTable.put(100, new JLabel("Large"));
        
        Dictionary<Integer, Component> labelTable2 = new Hashtable<Integer, Component>();
        labelTable2.put(100, new JLabel("Fast"));
        labelTable2.put(300, new JLabel("Medium"));
        labelTable2.put(500, new JLabel("Slow"));
        
        initComponents();
        
        settingSlider_blockSize.setLabelTable(labelTable);
        settingSlider_gameSpeed.setLabelTable(labelTable2);
       // addSlider(slider_blockSize, "Custom labels");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_about = new javax.swing.JDialog();
        aboutButton_ok = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dialog_settings = new javax.swing.JDialog();
        settingLabel_gameSpeed = new javax.swing.JLabel();
        settingLabel_fps = new javax.swing.JLabel();
        settingLabel_BlockSize = new javax.swing.JLabel();
        settingSlider_blockSize = new javax.swing.JSlider();
        settingSlider_fps = new javax.swing.JSlider();
        settingButton_cancel = new javax.swing.JButton();
        settingButton_ok = new javax.swing.JButton();
        settingSlider_gameSpeed = new javax.swing.JSlider();
        gameScreen = new tetris.display.Screen(1);
        background1 = new tetris.display.Background();
        menuBar = new javax.swing.JMenuBar();
        menu_game = new javax.swing.JMenu();
        checkBox_pause = new javax.swing.JCheckBoxMenuItem();
        menu_reset = new javax.swing.JMenuItem();
        radio_1p = new javax.swing.JRadioButtonMenuItem();
        radio_2p = new javax.swing.JRadioButtonMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menu_settings = new javax.swing.JMenuItem();
        menu_help = new javax.swing.JMenu();
        menu_about = new javax.swing.JMenuItem();

        dialog_about.setTitle("About");
        dialog_about.setResizable(false);
        dialog_about.setSize(new java.awt.Dimension(400, 550));

        aboutButton_ok.setText("OK");
        aboutButton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButton_okActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Methi    Skulsinlapakit");
        jTextArea2.setBorder(null);
        jTextArea2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea2.setEnabled(false);
        jTextArea2.setOpaque(false);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 30)); // NOI18N
        jLabel1.setText("Tetris");

        jLabel2.setText("Version 0.9.0");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Developers");

        javax.swing.GroupLayout dialog_aboutLayout = new javax.swing.GroupLayout(dialog_about.getContentPane());
        dialog_about.getContentPane().setLayout(dialog_aboutLayout);
        dialog_aboutLayout.setHorizontalGroup(
            dialog_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_aboutLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(aboutButton_ok)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_aboutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(165, 165, 165))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_aboutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dialog_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_aboutLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_aboutLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(156, 156, 156))))
            .addGroup(dialog_aboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_aboutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialog_aboutLayout.setVerticalGroup(
            dialog_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_aboutLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(aboutButton_ok)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        dialog_settings.setTitle("Game Settings");
        dialog_settings.setResizable(false);
        dialog_settings.setSize(new java.awt.Dimension(450, 330));

        settingLabel_gameSpeed.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        settingLabel_gameSpeed.setText("Game speed");

        settingLabel_fps.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        settingLabel_fps.setText("Frame Per Second");

        settingLabel_BlockSize.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        settingLabel_BlockSize.setText("Block size");

        settingSlider_blockSize.setMajorTickSpacing(50);
        settingSlider_blockSize.setPaintLabels(true);
        settingSlider_blockSize.setPaintTicks(true);
        settingSlider_blockSize.setSnapToTicks(true);

        settingSlider_fps.setMajorTickSpacing(15);
        settingSlider_fps.setMaximum(60);
        settingSlider_fps.setMinimum(15);
        settingSlider_fps.setPaintLabels(true);
        settingSlider_fps.setPaintTicks(true);
        settingSlider_fps.setSnapToTicks(true);
        settingSlider_fps.setValue(30);

        settingButton_cancel.setText("Cancel");

        settingButton_ok.setText("OK");
        settingButton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingButton_okActionPerformed(evt);
            }
        });

        settingSlider_gameSpeed.setMajorTickSpacing(200);
        settingSlider_gameSpeed.setMaximum(500);
        settingSlider_gameSpeed.setMinimum(100);
        settingSlider_gameSpeed.setPaintLabels(true);
        settingSlider_gameSpeed.setPaintTicks(true);
        settingSlider_gameSpeed.setSnapToTicks(true);
        settingSlider_gameSpeed.setValue(300);
        settingSlider_gameSpeed.setInverted(true);

        javax.swing.GroupLayout dialog_settingsLayout = new javax.swing.GroupLayout(dialog_settings.getContentPane());
        dialog_settings.getContentPane().setLayout(dialog_settingsLayout);
        dialog_settingsLayout.setHorizontalGroup(
            dialog_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_settingsLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(dialog_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dialog_settingsLayout.createSequentialGroup()
                        .addComponent(settingButton_cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(settingButton_ok))
                    .addGroup(dialog_settingsLayout.createSequentialGroup()
                        .addGroup(dialog_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(settingLabel_fps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(settingLabel_gameSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(settingLabel_BlockSize, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(dialog_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(settingSlider_blockSize, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(settingSlider_fps, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(settingSlider_gameSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        dialog_settingsLayout.setVerticalGroup(
            dialog_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_settingsLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(dialog_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settingSlider_fps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_settingsLayout.createSequentialGroup()
                        .addComponent(settingLabel_fps)
                        .addGap(15, 15, 15)))
                .addGroup(dialog_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_settingsLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(settingLabel_gameSpeed))
                    .addGroup(dialog_settingsLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(settingSlider_gameSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(dialog_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settingSlider_blockSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dialog_settingsLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(settingLabel_BlockSize)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(dialog_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingButton_cancel)
                    .addComponent(settingButton_ok))
                .addGap(43, 43, 43))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tetris");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(806, 646));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout gameScreenLayout = new javax.swing.GroupLayout(gameScreen);
        gameScreen.setLayout(gameScreenLayout);
        gameScreenLayout.setHorizontalGroup(
            gameScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameScreenLayout.createSequentialGroup()
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        gameScreenLayout.setVerticalGroup(
            gameScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameScreenLayout.createSequentialGroup()
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(gameScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menu_game.setText("Game");

        checkBox_pause.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.CTRL_MASK));
        checkBox_pause.setText("Pause game");
        checkBox_pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_pauseActionPerformed(evt);
            }
        });
        menu_game.add(checkBox_pause);

        menu_reset.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menu_reset.setText("Restart game");
        menu_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_resetActionPerformed(evt);
            }
        });
        menu_game.add(menu_reset);

        radio_1p.setSelected(true);
        radio_1p.setText("1 Player");
        radio_1p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_1pActionPerformed(evt);
            }
        });
        menu_game.add(radio_1p);

        radio_2p.setText("2 Players");
        radio_2p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_2pActionPerformed(evt);
            }
        });
        menu_game.add(radio_2p);
        menu_game.add(jSeparator2);

        menu_settings.setText("Settings...");
        menu_settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_settingsActionPerformed(evt);
            }
        });
        menu_game.add(menu_settings);

        menuBar.add(menu_game);

        menu_help.setText("Help");

        menu_about.setText("About...");
        menu_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_aboutMouseClicked(evt);
            }
        });
        menu_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_aboutActionPerformed(evt);
            }
        });
        menu_help.add(menu_about);

        menuBar.add(menu_help);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_resetActionPerformed
        
    }//GEN-LAST:event_menu_resetActionPerformed

    private void menu_aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_aboutMouseClicked
        
        javax.swing.JOptionPane.showMessageDialog(new javax.swing.JFrame(), "Would you like green eggs and ham?", "About Developers", javax.swing.JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_menu_aboutMouseClicked

    private void aboutButton_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButton_okActionPerformed
        dialog_about.dispose();
    }//GEN-LAST:event_aboutButton_okActionPerformed

    private void menu_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_aboutActionPerformed
        dialog_about.setVisible(true);
       // javax.swing.JOptionPane.showMessageDialog(new javax.swing.JFrame(), "Would you like green eggs and ham?", "About Developers", javax.swing.JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_menu_aboutActionPerformed

    private void checkBox_pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_pauseActionPerformed
        isPause = checkBox_pause.isSelected();
        if(isPause) {
            gameScreen.pause();
        }
        else {
            gameScreen.run();
        }
    }//GEN-LAST:event_checkBox_pauseActionPerformed

    private void menu_settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_settingsActionPerformed
        dialog_settings.setVisible(true);
    }//GEN-LAST:event_menu_settingsActionPerformed

    private void settingButton_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingButton_okActionPerformed
        dialog_settings.setVisible(false);
        dialog_settings.dispose();
        gameScreen.setting(settingSlider_fps.getValue(), settingSlider_gameSpeed.getValue());
    }//GEN-LAST:event_settingButton_okActionPerformed

    private void radio_1pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_1pActionPerformed
       
        if(radio_1p.isSelected()) {
            is2Player = false;
            radio_2p.setSelected(false);
        }
    }//GEN-LAST:event_radio_1pActionPerformed

    private void radio_2pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_2pActionPerformed

        if(radio_2p.isSelected()) {
            is2Player = true;
            radio_1p.setSelected(false);

        }
    }//GEN-LAST:event_radio_2pActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton_ok;
    private tetris.display.Background background1;
    private javax.swing.JCheckBoxMenuItem checkBox_pause;
    private javax.swing.JDialog dialog_about;
    private javax.swing.JDialog dialog_settings;
    private tetris.display.Screen gameScreen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menu_about;
    private javax.swing.JMenu menu_game;
    private javax.swing.JMenu menu_help;
    private javax.swing.JMenuItem menu_reset;
    private javax.swing.JMenuItem menu_settings;
    private javax.swing.JRadioButtonMenuItem radio_1p;
    private javax.swing.JRadioButtonMenuItem radio_2p;
    private javax.swing.JButton settingButton_cancel;
    private javax.swing.JButton settingButton_ok;
    private javax.swing.JLabel settingLabel_BlockSize;
    private javax.swing.JLabel settingLabel_fps;
    private javax.swing.JLabel settingLabel_gameSpeed;
    private javax.swing.JSlider settingSlider_blockSize;
    private javax.swing.JSlider settingSlider_fps;
    private javax.swing.JSlider settingSlider_gameSpeed;
    // End of variables declaration//GEN-END:variables
}
